export const products = [
  {
    id: 1,
    title: 'Nebula Protocol',
    category: 'Games',
    type: 'Adventure',
    price: 19.99,
    oldPrice: 39.99,
    rating: 4.9,
    reviews: 2847,
    badge: 'Best seller',
    art: 'nebula',
    description:
      'Wake aboard a silent research station and uncover a mystery that stretches across a fractured galaxy.',
  },
  {
    id: 2,
    title: 'Quiet Hours',
    category: 'Books',
    type: 'Fiction',
    price: 8.99,
    oldPrice: 14.99,
    rating: 4.8,
    reviews: 1924,
    badge: 'Editors pick',
    art: 'quiet',
    description:
      'A tender collection of stories about the people we become when the rest of the city goes to sleep.',
  },
  {
    id: 3,
    title: 'Apex Circuit',
    category: 'Games',
    type: 'Racing',
    price: 24.99,
    oldPrice: 49.99,
    rating: 4.7,
    reviews: 3512,
    badge: 'Trending',
    art: 'apex',
    description:
      'Build your dream machine and race through spectacular circuits where every second matters.',
  },
  {
    id: 4,
    title: 'Signal / Noise',
    category: 'Movies & TV',
    type: 'Documentary',
    price: 12.99,
    oldPrice: 18.99,
    rating: 4.9,
    reviews: 817,
    badge: 'Award winner',
    art: 'signal',
    description:
      'A cinematic documentary about the people designing the invisible systems that shape modern life.',
  },
  {
    id: 5,
    title: 'Solaris Drift',
    category: 'Games',
    type: 'Simulation',
    price: 17.99,
    oldPrice: 29.99,
    rating: 4.6,
    reviews: 1355,
    badge: 'New',
    art: 'solaris',
    description:
      'Pilot your own solar skiff, trade between settlements, and map a beautiful hand-built universe.',
  },
  {
    id: 6,
    title: 'Designing Calm',
    category: 'Books',
    type: 'Design',
    price: 10.99,
    oldPrice: 21.99,
    rating: 4.8,
    reviews: 643,
    badge: 'Staff pick',
    art: 'calm',
    description:
      'Practical tools for creating focused, humane digital experiences in an always-on world.',
  },
  {
    id: 7,
    title: 'Night Shift',
    category: 'Movies & TV',
    type: 'Thriller',
    price: 14.99,
    oldPrice: 24.99,
    rating: 4.5,
    reviews: 2201,
    badge: 'Popular',
    art: 'night',
    description:
      'One night. One missing package. One courier caught in the middle of a citywide conspiracy.',
  },
  {
    id: 8,
    title: 'Parallel Lines',
    category: 'Games',
    type: 'Puzzle',
    price: 11.99,
    oldPrice: 19.99,
    rating: 4.7,
    reviews: 936,
    badge: 'Indie gem',
    art: 'parallel',
    description:
      'Shift perspective and connect impossible paths in this meditative spatial puzzle adventure.',
  },
  {
    id: 9,
    title: 'The Long Weekend',
    category: 'Books',
    type: 'Mystery',
    price: 7.99,
    oldPrice: 12.99,
    rating: 4.6,
    reviews: 1508,
    badge: 'Page turner',
    art: 'weekend',
    description:
      'Six old friends, a remote house, and a secret that refuses to stay buried.',
  },
  {
    id: 10,
    title: 'Neon Divide',
    category: 'Games',
    type: 'Action',
    price: 29.99,
    oldPrice: 59.99,
    rating: 4.9,
    reviews: 4682,
    badge: 'Top rated',
    art: 'neon',
    description:
      'Choose your side and reshape a divided metropolis in a stylish, story-driven action epic.',
  },
  {
    id: 11,
    title: 'Small Worlds',
    category: 'Movies & TV',
    type: 'Animation',
    price: 9.99,
    oldPrice: 16.99,
    rating: 4.8,
    reviews: 1104,
    badge: 'Family favorite',
    art: 'worlds',
    description:
      'A bright animated journey through the tiny universes hiding in everyday places.',
  },
  {
    id: 12,
    title: 'The Better Habit',
    category: 'Books',
    type: 'Wellbeing',
    price: 6.99,
    oldPrice: 11.99,
    rating: 4.5,
    reviews: 729,
    badge: 'Reader favorite',
    art: 'habit',
    description:
      'A gentle, evidence-based guide to building routines that last without burning yourself out.',
  },
];

export const categories = [
  {
    name: 'Books',
    description: 'Ideas worth keeping',
    count: '1,240 titles',
    accent: 'violet',
  },
  {
    name: 'Games',
    description: 'Your next adventure',
    count: '860 worlds',
    accent: 'cyan',
  },
  {
    name: 'Movies & TV',
    description: 'Stories in motion',
    count: '2,100 picks',
    accent: 'coral',
  },
];
